### ISSUE TITLE
Able to "rearrange" pedestal words to non-anagrams

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#33]
I am able to rearrange the pedestal words from things like "byur" to "7" - which is (obviously) not an anagram - easy to lose what the words should be.

**Comment by michaelchadwick** [comment]
I wasn't sure exactly what the issue was until I read this issue a few times ;P

I get now that you're saying you shouldn't be able to just input nonsense, which is right on. Will fix.

**Comment by michaelchadwick** [comment]
Latest release fixes this.
