### ISSUE TITLE
Crash east of Massive Door

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#36]
[>>> SKY TOWER (MASSIVE DOOR) <<<]
Before you lies a massive collection of cumulus clouds that form into
a seemingly impenetrable door, beyond which may well be your doom.

> > Thing(s):   massive_door
> > Path(s):    east, west

[LV: 1][XP: 45][ROX: 67] [HP: 30/30 ][STM:20/20] [Arllile @ Sky Tower (Massive Door)]
 GW> e
- >>> *
  bad value for range
  ######################################################################
  Gem Warrior played for 10 minutes, 18 seconds, and 239 milliseconds
  ----------------------------------------------------------------------
  Player killed 7 monster(s)
     picked up 14 item(s)
     traveled 69 time(s)
     rested 15 time(s)
     died 1 time(s)
  ######################################################################

**Comment by michaelchadwick** [comment]
YAML got me on this one. Fixed in [0.9.26](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.26).
