### ISSUE TITLE
Unable to load on OS Xdue to win32-sound

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#38]
/Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': no implicit conversion of Symbol into String. (LoadError)
Could not open library 'libkernel32.dylib': dlopen(libkernel32.dylib, 5): image not found
    from /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in`map'
    from /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
    from /Library/Ruby/Gems/2.0.0/gems/win32-sound-0.6.0/lib/win32/windows/functions.rb:12:in`module:SoundFunctions'
    from /Library/Ruby/Gems/2.0.0/gems/win32-sound-0.6.0/lib/win32/windows/functions.rb:4:in `<module:Windows>'
    from /Library/Ruby/Gems/2.0.0/gems/win32-sound-0.6.0/lib/win32/windows/functions.rb:3:in`<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/win32-sound-0.6.0/lib/win32/sound.rb:1:in `require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/win32-sound-0.6.0/lib/win32/sound.rb:1:in`<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.26/lib/gemwarrior/misc/music.rb:5:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.26/lib/gemwarrior/game.rb:11:in`require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.26/lib/gemwarrior/game.rb:11:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.26/bin/gemwarrior:5:in`require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.26/bin/gemwarrior:5:in `<top (required)>'
    from /usr/bin/gemwarrior:23:in`load'
    from /usr/bin/gemwarrior:23:in `<main>'

**Comment by michaelchadwick** [comment]
Fixed in [0.9.27](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.27).
