### ISSUE TITLE
Crash on Attack: undefined local variable or method `slow' for #

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#39]
<pre>
[LV: 1][XP:  3][ROX:  0] [HP: 30/30 ][STM:20/20] [Canthe @ Cave (Antechamber)]
 GW> a amethystle
******************************
You decide to attack amethystle!
amethystle cries out: "You've found yourself in quite the thorny issue!"

CANTHE       ::  30 HP
AMETHYSTLE   :: ??? HP

What do you do?
[Fight/Attack][Defend][Look][Pass][Run]
a
You attack amethystle with your stone!
> You wound amethystle for undefined local variable or method `slow' for #<Gemwarrior::Battle:0x007fe2cca7c7e8>
######################################################################
Gem Warrior v0.9.27 played for 0 mins, 40 secs, and 459 ms
----------------------------------------------------------------------
Player killed 0 monster(s)
       picked up 3 item(s)
       traveled 2 time(s)
       rested 0 time(s)
       died 0 time(s)
######################################################################
</pre>

**Comment by messerman** [comment]
It happens when the monster attacks first, too:

<pre>
[LV: 1][XP:  3][ROX:  0] [HP: 30/30 ][STM:20/20] [Frarar @ Cave (Dropoff)]
 GW> attack aquamarine
******************************
You decide to attack aquamarine!
aquamarine cries out: "Attention! You are about to get smashed!"
aquamarine strikes first!
aquamarine attacks you!
> You are wounded for undefined local variable or method `slow' for #<Gemwarrior::Battle:0x007fb424406070>
######################################################################
Gem Warrior v0.9.27 played for 0 mins, 26 secs, and 741 ms
----------------------------------------------------------------------
Player killed 0 monster(s)
       picked up 6 item(s)
       traveled 6 time(s)
       rested 0 time(s)
       died 0 time(s)
######################################################################
</pre>

**Comment by michaelchadwick** [comment]
Hash style update unintentional bug got introduced. Man, I could really use some testing. Fixed in [0.9.28](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.28).
