### ISSUE TITLE
Spoils of war not in inventory after battle

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#40]
<pre>
You have defeated alexandrat!

You get the following spoils of war:
 XP   : 2
 ROX  : 5
 ITEMS: herb
******************************

[LV: 1][XP:  3][ROX:  0] [HP: 27/30 ][STM:20/20] [Macketa @ Cave (Entrance)]
 GW> use herb
You cannot use that, as it does not exist here or in your inventory.

[LV: 1][XP:  3][ROX:  0] [HP: 27/30 ][STM:20/20] [Macketa @ Cave (Entrance)]
 GW> use herb
You cannot use that, as it does not exist here or in your inventory.

[LV: 1][XP:  3][ROX:  0] [HP: 27/30 ][STM:20/20] [Macketa @ Cave (Entrance)]
 GW> i
letter, stone, tent
</pre>

and again

<pre>
You have defeated alexandrat!

You get the following spoils of war:
 XP   : 2
 ROX  : 5
 ITEMS: herb
******************************

[LV: 1][XP:  3][ROX:  0] [HP: 24/30 ][STM:20/20] [Macketa @ Plains (South of River)]
 GW> i
letter, stone, tent, stalactite, stonemite, map
</pre>

**Comment by messerman** [comment]
Also note, XP and ROX do not go up, either.

**Comment by michaelchadwick** [comment]
Fixed in [0.9.29](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.29).
