### ISSUE TITLE
'use tent' crash

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#41]
Using a tent when you are injured causes a crash (reproducibly). This does not happen if you are not injured when you 'use tent' nor when you 'rest'.

<pre>
[LV: 1][XP:  9][ROX: 17] [HP: 15/30 ][STM:20/20] [Amaic @ Plains (Outskirts)]
 GW> use tent
tent can be used 3 more time(s).
** ZZZZZ **
You brandish the trusty magical canvas and, with a flick of the wrist, your home
for the evening is set up. Approximately 8 hours, 12 minutes, and 41 seconds
later, you wake up, fully rested, ready for adventure.
undefined method `gsub' for 30:Fixnum
######################################################################
Gem Warrior v0.9.30 played for 2 mins, 21 secs, and 405 ms
----------------------------------------------------------------------
Player killed 3 monster(s)
       picked up 3 item(s)
       traveled 12 time(s)
       rested 2 time(s)
       died 1 time(s)
######################################################################
</pre>

**Comment by michaelchadwick** [comment]
Fixed in [0.9.31](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.31).
