### ISSUE TITLE
Mercantile Crash

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#42]
<pre>
Rockney's Hole in the Wall
--------------------------
(1) Herb     - 10  rox
(2) Dagger   - 150 rox

>>"What are you in need of?"
 1 - Herb
 2 - Dagger
 x - leave
x
>>"If you need anything further, I'm always in this hole..."
undefined method `gsub' for []:Array
######################################################################
Gem Warrior v0.9.30 played for 2 mins, 9 secs, and 140 ms
----------------------------------------------------------------------
Player killed 3 monster(s)
       picked up 6 item(s)
       traveled 17 time(s)
       rested 2 time(s)
       died 0 time(s)
######################################################################
</pre>

**Comment by michaelchadwick** [comment]
Fixed in [0.9.31](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.31).
