### ISSUE TITLE
Useable but non-useable object (couch)

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#43]
<pre>
[>>> SKY TOWER (LOUNGE) <<<]
Nothing but a simple couch, which looks very comfortable, exists in
this corner of the tower.
>> Thing(s):   couch
>> Path(s):    south, west

[LV: 1][XP: 31][ROX: 40] [HP: 30/30 ][STM:20/20] [Coren @ Sky Tower (Lounge)]
 GW> look couch
Ever wanted to sit on a cloud? Now is your chance.

[LV: 1][XP: 31][ROX: 40] [HP: 30/30 ][STM:20/20] [Coren @ Sky Tower (Lounge)]
 GW> use couch
You come to rest on the impossibly soft surface of the furniture, but even after
a few minutes of this seemingly heavenly hedonism you don't feel significantly
better and decide to get up again.
You cannot use that, as it does not exist here or in your inventory.
</pre>

**Comment by michaelchadwick** [comment]
Fixed in [0.9.31](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.31).
