### ISSUE TITLE
Crash going "north" of waterfall

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#44]
<pre>
[>>> SKY TOWER (WATERFALLS) <<<]
The seemingly neverending deluge of water causes this room to be quite
loud, yet pretty.
>> Thing(s):   waterfall
>> Path(s):    north, east

[LV: 1][XP: 31][ROX: 40] [HP: 30/30 ][STM:20/20] [Coren @ Sky Tower (Waterfalls)]
 GW> look waterfall
Gallons of murky, sparkling water fall downward from an unknown spot in the sky,
ending in a pool on the ground, yet never overflowing.

[LV: 1][XP: 31][ROX: 40] [HP: 30/30 ][STM:20/20] [Coren @ Sky Tower (Waterfalls)]
 GW> use waterfall
You stretch out your hand and touch the waterfall. It stings you with its cold
and forceful gushing. Your hand is now wet and rougher than before. In time, it
will dry.

[LV: 1][XP: 31][ROX: 40] [HP: 29/30 ][STM:20/20] [Coren @ Sky Tower (Waterfalls)]
 GW> n
* ^^^ *
undefined method `checked_for_monsters=' for nil:NilClass
######################################################################
Gem Warrior v0.9.30 played for 11 mins, 47 secs, and 70 ms
----------------------------------------------------------------------
Player killed 9 monster(s)
       picked up 9 item(s)
       traveled 85 time(s)
       rested 15 time(s)
       died 4 time(s)
######################################################################
</pre>

**Comment by michaelchadwick** [comment]
Fixed in [0.9.31](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.31).
