### ISSUE TITLE
Request: Allow Version (v) to display version while in game.

### ISSUE THREAD

**Issue by thatmacguy** [michaelchadwick/gemwarrior#47]
This could help with debugging.  

Perhaps also allow to check for updates in game; at least while updates are being quickly ...

**Comment by michaelchadwick** [comment]
Good idea on both, although I'm planning on implementing save/load, which will necessitate a path back to the main menu, which could handle both of these cases and some.

**Comment by michaelchadwick** [comment]
The former is in [0.9.36](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.9.36).

**Comment by michaelchadwick** [comment]
The latter has been added to [0.10.4](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.10.4).
