### ISSUE TITLE
Crash on startup (0.9.36)

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#48]
<pre>
#> gemwarrior
An unexpected error occurred while running Gem Warrior:
  undefined method `[]' for nil:NilClass
</pre>

**Comment by messerman** [comment]
Running on OS X.

**Comment by michaelchadwick** [comment]
Please update to 0.9.37.

**Comment by messerman** [comment]
Same error.

**Comment by michaelchadwick** [comment]
Hmmm. Cannot reproduce on either test system (OS X 10.10.4, Win7-64). You sure you have `gemwarrior -v` -> `Gem Warrior v0.9.37`?

**Comment by messerman** [comment]
Unable to run "gemwarrior -v" - same error, but gem list --local shows that I'm running 0.9.37

I ran in the debugger - see if this helps.

<pre>
#  ruby -d bin/gemwarrior
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:1087 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:1096 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- colorize
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- matrext
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/misc/name_generator.rb:42: warning: assigned but unused variable - i
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/misc/name_generator.rb:120: warning: shadowing outer local variable - subkey
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/misc/name_generator.rb:139: warning: assigned but unused variable - i
Exception `NameError' at /Library/Ruby/Gems/2.0.0/gems/psych-2.0.13/lib/psych/class_loader.rb:67 - uninitialized constant BigDecimal
Exception `NameError' at /Library/Ruby/Gems/2.0.0/gems/psych-2.0.13/lib/psych/class_loader.rb:67 - uninitialized constant DateTime
Exception `NameError' at /Library/Ruby/Gems/2.0.0/gems/psych-2.0.13/lib/psych/core_ext.rb:16 - method `to_yaml' not defined in Object
Exception `NameError' at /Library/Ruby/Gems/2.0.0/gems/psych-2.0.13/lib/psych/core_ext.rb:29 - method `yaml_as' not defined in Module
Exception `NameError' at /Library/Ruby/Gems/2.0.0/gems/psych-2.0.13/lib/psych/deprecated.rb:81 - undefined method `to_yaml_properties' for class `Object'
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/misc/wordlist.rb:108: warning: assigned but unused variable - error
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- http
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- idn
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:141 - cannot load such file -- idn
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:141 - cannot load such file -- idn
/Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http/options.rb:77: warning: method redefined; discarding old follow=
/Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http/options.rb:86: warning: method redefined; discarding old persistent=
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http/client.rb
    from bin/gemwarrior:5:in `<main>'
    from bin/gemwarrior:5:in `require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/game.rb:7:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/game.rb:7:in `require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/entities/player.rb:10:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/entities/player.rb:10:in `require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/misc/wordlist.rb:4:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http.rb:8:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http/client.rb:6:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/http-0.9.1/lib/http/connection.rb:3:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Using Ext extension for JSON.
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/entities/item.rb:19: warning: method redefined; discarding old use
/Library/Ruby/Gems/2.0.0/gems/gemwarrior-0.9.37/lib/gemwarrior/arena.rb:24: warning: assigned but unused variable - is_arena
/Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
/Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- os
/Library/Ruby/Gems/2.0.0/gems/os-0.9.6/lib/os.rb:154: warning: mismatched indentations at 'end' with 'for' at 151
/Library/Ruby/Gems/2.0.0/gems/os-0.9.6/lib/os.rb:158: warning: assigned but unused variable - kb
/Library/Ruby/Gems/2.0.0/gems/os-0.9.6/lib/os.rb:198: warning: mismatched indentations at 'end' with 'def' at 190
/Library/Ruby/Gems/2.0.0/gems/os-0.9.6/lib/os.rb:240: warning: mismatched indentations at 'end' with 'case' at 218
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- clocker
Exception `LoadError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- github_api
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/ext/faraday.rb:15: warning: method redefined; discarding old to_query
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/utils.rb:152: warning: previous definition of to_query was here
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/ext/faraday.rb:20: warning: method redefined; discarding old build_nested_query
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/utils.rb:167: warning: previous definition of build_nested_query was here
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/jsonable.rb:12: warning: `*' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/jsonable.rb:14: warning: `*' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:26: warning: `*' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:28: warning: `*' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:199: warning: assigned but unused variable - matched_callbacks
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:28: warning: method redefined; discarding old per_page
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:28: warning: method redefined; discarding old auto_pagination
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:35: warning: method redefined; discarding old auto_pagination=
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/api.rb:35: warning: method redefined; discarding old per_page=
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/authorizations/app.rb:52: warning: assigned but unused variable - e
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/markdown.rb:52: warning: assigned but unused variable - mime_type
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/repos.rb:268: warning: assigned but unused variable - params
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/repos.rb:328: warning: assigned but unused variable - params
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/repos/collaborators.rb:24: warning: assigned but unused variable - params
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/client/repos/releases/assets.rb:38: warning: assigned but unused variable - params
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/request/jsonize.rb:35: warning: assigned but unused variable - type
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:169: warning: method redefined; discarding old include?
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:169: warning: previous definition of include? was here
/Library/Ruby/Gems/2.0.0/gems/github_api-0.12.4/lib/github_api/response_wrapper.rb:81: warning: method redefined; discarding old []
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:169: warning: previous definition of [] was here
/Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
/Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
Exception `NoMethodError' at bin/gemwarrior:30 - undefined method `[]' for nil:NilClass
An unexpected error occurred while running Gem Warrior:
  undefined method `[]' for nil:NilClass
</pre>

**Comment by michaelchadwick** [comment]
Try deleting your `~/.gemwarrior_options` file and then running the command
again. Methinks I need to tweak the code that checks that file to make sure
it isn't reading stuff that isn't there.

**Comment by messerman** [comment]
With version 0.10.0 it gave me the error:
An unexpected error occurred while running Gem Warrior:
  File exists - /Users/mmesserman/.gemwarrior

When I removed that file I was able to load.

**Comment by michaelchadwick** [comment]
I changed up where the config/save files get put on your system, so this was probably expected.
