### ISSUE TITLE
feep crash

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#49]
<pre>[LV: 1][XP:  3][ROX:  0] [HP: 30/30 ][STM:20/20] [Jonne @ Plains (South of River)]
 GW> attack amethystle
******************************
You decide to attack amethystle!
amethystle cries out: "You've found yourself in quite the thorny issue!"
amethystle strikes first!
amethystle attacks you!
> You are wounded for gemwarrior: 
feep -h for usage
7######################################################################
Gem Warrior v0.10.0 played for 0 min(s), 57 sec(s), and 734 ms
----------------------------------------------------------------------
Jonne      killed 0 monster(s)
           picked up 3 item(s)
           traveled 3 time(s)
           rested 0 time(s)
           died 0 time(s)
######################################################################
Saving game...
4Game saved!
</pre>

---

On the plus side, the game loaded right back in that spot!

**Comment by michaelchadwick** [comment]
Feep is buggier than I thought, so this won't be resolved anytime soon. For now, use at your own risk!

Also, I've addressed this by adding the ability to change the sound system in the main menu and putting a note about feep being buggy.

**Comment by michaelchadwick** [comment]
Found a new sound system I can use, [bloopsaphone](https://github.com/mental/bloopsaphone), that will work for the Mac as a default. Added in version [0.14.5](https://github.com/mental/bloopsaphone). Feep is still around for fun, but it is no longer recommended.
