### ISSUE TITLE
Crash on winning

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#50]
<pre>
  [Fight/Attack][Defend][Look][Pass][Run]
  [BATTLE]> a
  You attack Emerald with your opalaser!
  > You wound Emerald for 19 point(s)!
  YOU HAVE DEFEATED EMERALD!

<^><^><^><^><^><^><^><^><^><^>
You beat Emerald! You win!
You receive the SparklyThing(tm) and become the true Gem Warrior!
You decide to ignore Queen Ruby and take your spoils back home
where you live out the rest of your days staring at it, wondering
what it was all about.

Thank you for playing. Goodbye.
<^><^><^><^><^><^><^><^><^><^>
look
######################################################################
Gem Warrior v0.10.7 played for 1556 min(s), 7 sec(s), and 965 ms
----------------------------------------------------------------------
Jonne      killed 115 monster(s)
           picked up 14 item(s)
           traveled 390 time(s)
           rested 168 time(s)
           died 12 time(s)
######################################################################
Saving game...
Game saved!
</pre>

The same thing happens regardless of what you do after the "Thank you for playing. Goodbye." message.

**Comment by messerman** [comment]
Also, when you come back afterwards, Emerald is alive again.

**Comment by michaelchadwick** [comment]
Now that it saves your game and your "session" can conceivably go on for a lot longer, apparently I need a new "hour(s)" part of the duration message at the end ;P

Also, I need to figure out what to do when you actually win the game! What do you think? Kick you back to the main menu and erase your save? Want to be able to go back into the game even after killing Emerald? I may extend the "story" as it were beyond that event, but it's not created yet.

**Comment by messerman** [comment]
Maybe pull a LoZ and do a master quest where everything is harder? Once I
beat the 8 or so copies of Garynetta I was able to beat Emerald with a fair
amount of ease. Garynetta killed me more than anything else. Access to a
new world? More difficult monsters, bigger/badder weapons?

Feature suggestions: more tents, bed/couch heal you for more on "use" than
resting on the ground, ability to "rest" until healed, ability to look at
items before you buy them, more levels to weaponry (most rock and
stalagtite attack for same, but gun is easy to find, infinite, and hits for
much more - and then dagger isn't better and I had to buy that), more NPCs.

Incidentally, the "rest" crash is still happening for me.

## 

# Matt Messerman messerman@gmail.com

"I ate too much gumbo", said Tom, ruefully.

On Tue, Aug 18, 2015 at 11:15 AM, Michael Chadwick <notifications@github.com

**Comment by michaelchadwick** [comment]
Thanks for all the suggestions. I've added them (as well as a bunch of
other ideas they triggered) to an internal list and will add them as I go.

**Comment by michaelchadwick** [comment]
Also, just fyi, it was a feature, not a bug, that the game "crashed" on beating Emerald. It was more like a "Yay, you won! Now the game ends." Now that the game saves on exit, the behavior looks a little more confusing. So, I'll think about how to handle this and change that.

**Comment by michaelchadwick** [comment]
The ending has been updated significantly. Grab [0.11.0](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.11.0)!
