### ISSUE TITLE
Quit Crash

### ISSUE THREAD

**Issue by messerman** [michaelchadwick/gemwarrior#51]
<pre>
/-+-+-+ +-+-+-+-+-+-+-\
|G|E|M| |W|A|R|R|I|O|R|
\-+-+-+ +-+-+-+-+-+-+-/

      GW v0.10.8
=======================
 (N)ew Game
 (R)esume Game
 (A)bout
 (H)elp
 (O)ptions
 (L)og of Attempts
 (C)heck for Updates
 (E)xit
=======================

> Resuming game...
[>>> SKY TOWER (MASSIVE DOOR) <<<]
Before you lies a massive collection of cumulus clouds that form into
a seemingly impenetrable door, beyond which may well be your doom.
>> Thing(s):    massive_door
>> Path(s):     east, west

[LV: 6][XP:1318][ROX:899] [HP: 85/85 ][STM:60/60] [Jonne @ Sky Tower (Massive Door)]
 GW> quit
You sure you want to quit? (y/n) y
undefined local variable or method `answer' for #<Gemwarrior::Evaluator:0x007f8e21b31b98>
######################################################################
Gem Warrior v0.10.8 played for 2676 min(s), 1 sec(s), and 282 ms
----------------------------------------------------------------------
Jonne      killed 118 monster(s)
           killed  boss(es)
           picked up 14 item(s)
           traveled 395 time(s)
           rested 184 time(s)
           died 12 time(s)
######################################################################
Saving game...
Game saved!
</pre>

**Comment by michaelchadwick** [comment]
Good eye. I never use the confirmation exit, so that bug has probably been
around for a while now. It's fixed in dev and will go out with my next
batch of changes.

**Comment by thatmacguy** [comment]
yup, I got this error too:

```
 GW> q
You sure you want to quit? (y/n) n
undefined local variable or method `answer' for #<Gemwarrior::Evaluator:0x007fc42304f2b0>
```

**Comment by michaelchadwick** [comment]
The new version, [0.11.0](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.11.0), should have fixed this (as well as added MANY things).
