### ISSUE TITLE
File exists error on first launch of gemwarrior-0.10.8

### ISSUE THREAD

**Issue by thatmacguy** [michaelchadwick/gemwarrior#52]
god$ gemwarrior 
An unexpected error occurred while running Gem Warrior:
  File exists - /Users/god/.gemwarrior

(to be fair, i manually created this file a long time ago...)

**Comment by michaelchadwick** [comment]
GW now uses a directory named the same thing, and so it's trying to create
that, but the old .gemwarrior file probably still exists, so delete it and
let the game remake it.

**Comment by thatmacguy** [comment]
Yup, that's what I did...  Just annoying you with yet another file check...
