### ISSUE TITLE
Inventory consolidation

### ISSUE THREAD

**Issue by thatmacguy** [michaelchadwick/gemwarrior#54]
Feature request:
combine inventory so that

```
letter, stone, tent, herb, herb, bullet, bullet, bullet, feather, bullet, bullet
```

becomes

```
letter, stone, tent, 2 herbs, 5 bullets, and a feather.
```

**Comment by michaelchadwick** [comment]
Time to change arrays to hashes!

**Comment by michaelchadwick** [comment]
This has been added in [0.12.0](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.12.0). However, saves will not work if you upgrade because of another change I made (unless you run a small find-and-replace on them, which I can help with if need be).
