### ISSUE TITLE
room name should be highlighted in some way

### ISSUE THREAD

**Issue by michaelchadwick** [michaelchadwick/gemwarrior#8]

**Comment by michaelchadwick** [comment]
Is this concerning the main prompt (`[user @ location]`), or the name of the location above its description when you do a 'look' (`[ location ]`)? Regardless of which, what kind of highlighting should be done?

**Comment by messerman** [comment]
I was thinking of above the "look" description - bold it and/or make it a different/brighter color.

**Comment by michaelchadwick** [comment]
I've done this and changed the colors of the entities you encounter in each room so they stand out better, too. Check the newest version.
